### PR TITLE
magnetosphere and two-stream applications

### PR DESCRIPTION
**Pull request by liangwang0734**
```
│   ├── magnetospheres
│   │   └── generate-magnetosphere-3d-10m.py
│   └── two-stream
│       └── genreate-two-stream-5m.py
```

### CODE REVIEW

**Comment by cwsmith** [comment]
@liangwang0734 Thank you.

Pasting your message from slack with instructions for running the two-stream script:

> to generate a 5-moment script for two-stream instability using two processors and drift velocity / thermal velocity ratio = 3 (there are more options):
python generate-rt-two-stream-5m.py two-stream-5m.lua --nprocs 2 --vDrift__vTe 3.0

What is the equivalent command for the magnetosphere script?

For each application we also need to know:
- what inputs are exposed to the user and what are valid ranges for those inputs
- what post processing should be performed by default

Thanks again.

**Review by cwsmith — CHANGES_REQUESTED** [review]
Would you please remove the `apps` directory?  We can have one directory per application in the top level of the repo.

**Comment by liangwang0734** [comment]
> Would you please remove the `apps` directory? We can have one directory per application in the top level of the repo.

done

**Comment by cwsmith** [comment]
@liangwang0734 Thanks for adding the README files and removing the apps dir.  

It looks like each python script takes several arguments.  Should those all be exposed to the gateway user?  If so, what are valid input ranges for each?

Also, please provide guidance on what default post-processing should be run for each app.

**Comment by liangwang0734** [comment]
@cwsmith I am going to add restrictions on the parameters, along with info useful for admins.

I believe these scripts are intended to be used by the admins. The users still rely on the online interface.

For the two-stream cases, I tried to expose only the most essential parameters:
```
  --vDrift__vTe VDRIFT__VTE
                        drift velocity / thermal velocity
  --kx_de KX_DE         wavenumber * Debye length
  --pert PERT           perturbation magnitude to the uniform background density
  --tEnd_wpe TEND_WPE   simulation time * plasma frequency
  --nFrame NFRAME       number of output frames excluding the initial condition
  --Nx NX               number of cells for discretization
  --nProcs NPROCS       number of processors for parallel computing
```

The magnetosphere simulation has way more parameters as it is a more complicated problem.

At some point, we may need to make the interface more compact and structured, so that many of the secondary parameters are concealed by default but may be easily shown.

**Comment by liangwang0734** [comment]
@cwsmith I added range restrictions on exposed parameters in the two-fluid case to explore for an mechanism; does it look ok to you?:

https://github.com/SCOREC/vlabApps/pull/1/commits/2e6ad5f48611c7f84845b2d98a536747960ce91b

For example, the following would lead to errors:
```
liang@pop-os:~/src/vlabApps/two-stream$ python genreate-two-stream-5m.py test.lua --vDrift__vTe 103da
genreate-two-stream-5m.py: error: argument --vDrift__vTe: 103da not a valid value of type <class 'float'>


liang@pop-os:~/src/vlabApps/two-stream$ python genreate-two-stream-5m.py test.lua --vDrift__vTe 103
genreate-two-stream-5m.py: error: argument --vDrift__vTe: 103.0 is greater than the upper limit 100.0


liang@pop-os:~/src/vlabApps/two-stream$ python genreate-two-stream-5m.py test.lua --vDrift__vTe 0.001
genreate-two-stream-5m.py: error: argument --vDrift__vTe: 0.001 is smaller than the lower limit 0.1
```

**Comment by cwsmith** [comment]
@liangwang0734 I can see ranges in the two-stream script. That is perfect.  Thank you.

**Comment by JunoRavin** [comment]
@cwsmith For post processing, we will generally want to visualize the final outputs of the simulation from the output data. So for a given 5 moment run that uses some number of plasma species (electrons + ions for GEM, two electron species for the two-stream instability @liangwang0734 just committed) we will want to visualize the entirety of the output file. At the command line for us that is:

pgkyl input_file_species_nm_1.bp plot

for every species in the plasma.

We will also always want to visualize the output electromagnetic fields. Because the field object contains some outputs which are not typically useful for a user, that plotting command at the command line is:

pgkyl input_file_field_1.bp select --comp 0:6 plot
(only plot the first 6 components: Ex, Ey, Ez, Bx, By, Bz)

For 2D simulations, it is useful to add certain elements to the plot command such as:
plot -a (fixed aspect ratio; shows the current layer elongation in GEM)
plot --xlabel '$x/d_i$' --ylabel '$y/d_i$' (label the axes with the code normalization so we know how big the simulation is in terms of ion inertial lengths or some other reference value)

For the two-stream case @liangwang0734 committed, I believe the following command fill work and yield a valuable output:
pgkyl two-stream-5m_fieldEnergy.bp select --comp 0 growth -d plot --logy -f0

which should plot both the growing electric field along with a fit to the growing electric field that shows the growth rate of the instability.

**Comment by cwsmith** [comment]
## meeting notes 9/21

attendees: @liangwang0734 @cwsmith 

- magnetosphere
  - requires 10s or 100s of CPU cores for production usage
  - default parameters allow running on 1, 2 or 4 cores - default grid is very coarse
  - set `tEnd` to limit the runtime for demo/testing
  - Liang will add post-processing commands for 2d cuts
  - no input range restrictions yet - Cameron will make some guesses 
- two-stream
  - has value ranges and plotting commands
  - description is in lua script
- buenman
  - has value ranges and plotting commands
  - description is in lua script
- weibel
  - has value ranges and plotting commands
  - description is in lua script
  - process count range looks like copy-paste from `Nx` - a 1d problem should only need one or two cores?
- LAPD
  - Cameron will share proxy/pseudo/simplified inputs provided by Jason
- categories
  - basic: buneman, weibel, two-stream, gem reconnection
  - space: magnetosphere
  - lab: LAPD
- Experiment dashboard layout control
  - Can we control the layout of experiments on the dashboard so they are grouped by category?  
  - Can we add images for each app and/or category?
  - the following rendering created by @liangwang0734 shows the general idea/layout - the 'toggle button' shows and hides the apps in each category
- By Monday I expect we can have screenshots of most of the Apps
  - Cameron will add the apps tomorrow from the PR branch
  - @liangwang0734 will make the screenshots for Ammar's talk
  
image

**Review by cwsmith — APPROVED** [review]
Thank you.

**Pull request merged**
